### ISSUE TITLE
::slotted selector can‘t work correctly

### ISSUE THREAD

**Issue by lhbdhr** [vuejs/docs#2704]
https://vuejs.org/api/sfc-css-features.html#slotted-selectors

**::slotted** doesn't work, but **::v-slotted** works well, is it the doc wrong?
```css
.dropdown-option.is-disabled ::slotted(*) {                     /* doesn't work */
  color: #6c757d !important;
  pointer-events: none;
  background-color: transparent;
}
```

```css
.dropdown-option.is-disabled ::v-slotted(*) {                 /* works well */
  color: #6c757d !important;
  pointer-events: none;
  background-color: transparent;
}
```
